services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: |
      corepack enable
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          property: host
