services:
  - type: web
    name: n8n
    env: node
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_PORT
        value: 5678
